requires = ["tox>=4"]
env_list = ["lint", "3.12"]


[env_run_base]
description = "run unit tests"
deps = ["pytest>=8"]
skip_install = true
allowlist_externals = ["poetry"]
commands = [
    ["poetry", "install"],
    ["pytest", "tests/unit", "-vv"]
]

[env.lint]
description = "run linters"
skip_install = true
deps = ["black"]
commands = [["black", { replace = "posargs", default = ["."], extend = true} ]]
